config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig

from . import views

app_name = MailingConfig.name

urlpatterns = [
    path("", views.ListIndex.as_view(), name="home_page"),
    path("list_recipient/", views.MailingRecipientView.as_view(), name="recipient_list"),
    path("list_messages/", views.MessageView.as_view(), name="messages_list"),
    path("list_newsletter/", views.NewsletterView.as_view(), name="newsletter_list"),
    path("recipient/create/", views.MailingRecipientCreateView.as_view(), name="recipient_create"),
    path("message/create/", views.MessageCreateView.as_view(), name="message_create"),
    path("newsletter/create/", views.NewsletterCreateView.as_view(), name="newsletter_create"),
    path("recipient/detail/<slug:slug>/", views.MailingRecipientDetailView.as_view(), name="recipient_detail"),
    path("message/detail/<int:pk>/", views.MessageDetailView.as_view(), name="message_detail"),
    path("newsletter/detail/<int:pk>/", views.NewsletterDetailView.as_view(), name="newsletter_detail"),
    path("recipient/update/<slug:slug>/", views.MailingRecipientUpdateView.as_view(), name="recipient_update"),
    path("message/update/<int:pk>/", views.MessageUpdateView.as_view(), name="message_update"),
    path("newsletter/update/<int:pk>/", views.NewsletterUpdateView.as_view(), name="newsletter_update"),
    path("recipient/delete/<slug:slug>/", views.MailingRecipientDeleteView.as_view(), name="recipient_delete"),
    path("message/delete/<int:pk>/", views.MessageDeleteView.as_view(), name="message_delete"),
    path("newsletter/delete/<int:pk>/", views.NewsletterDeleteView.as_view(), name="newsletter_delete"),
    path("list_newsletter/moderation/", views.ModerationNewsletterView.as_view(), name="moderation_newsletter_list"),
    path(
        "list_recipient/moderation/", views.ModerationMailingRecipientView.as_view(), name="moderation_recipient_list"
    ),
    path("list_users/moderation/", views.ModerationUsersView.as_view(), name="moderation_user_list"),
    path("newsletter/moderation/<int:pk>/block/", views.ModerationNewsletterView.as_view(), name="moderation"),
    path("users/moderation/<int:pk>/block/", views.ModerationUsersView.as_view(), name="block_user"),
]

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig

from . import views
from .forms import UserPasswordResetForm, UserSetPasswordForm

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home_page"), name="logout"),
    path("confirm/<str:token>/", views.email_verification, name="verification"),
    # Смена пароля
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            form_class=UserPasswordResetForm,
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=UserSetPasswordForm,
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    # Работа с профилем
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="profile"),
    path("profile_update/<int:pk>/", views.UserUpdateView.as_view(), name="profile_update"),
]

mailing/forms.py
from django import forms
from transliterate import translit

from mailing.models import MailingRecipient, Message, Newsletter


class MixinForms:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class MailingRecipientForm(MixinForms, forms.ModelForm):

    class Meta:
        model = MailingRecipient
        fields = [
            "last_name",
            "first_name",
            "patronymic",
            "slug",
            "email",
            "comment",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "slug" not in self.initial:
            self.fields["slug"].initial = "default-slug"

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        slug = cleaned_data.get("slug")

        if first_name and last_name and "default-slug" in slug:
            generated_slug = f"{first_name}-{last_name}"
            cleaned_data["slug"] = translit(generated_slug.lower(), "ru", reversed=True)

        return cleaned_data


class MessageForm(MixinForms, forms.ModelForm):

    class Meta:
        model = Message
        fields = [
            "title",
            "body_message",
        ]


class NewsletterForm(MixinForms, forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = [
            "name",
            "recipients",
            "text",
            "status",
        ]

    def __init__(self, *args, **kwargs):
        # делаем фильтрацию форм для авторизованных пользователей
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        if self.user is not None:
            self.fields["text"].queryset = Message.objects.filter(owner=self.user)
            self.fields["recipients"].queryset = MailingRecipient.objects.filter(owner=self.user)

mailing/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView

from users.models import ModelUser

from .forms import MailingRecipientForm, MessageForm, NewsletterForm
from .mixins import CachedViewMixin
from .models import AttemptToSend, MailingRecipient, Message, Newsletter
from .services import CachedCreateView, CachedDeleteView, CachedListView, CachedUpdateView, IndexCounter

menu = [
    {
        "title": "Получатель рассылки",
        "list": "Список получателей",
        "create": "Создать",
        "update": "Обновить данные",
        "delete": "Удалить",
        "unique": "unic1",
        "url": "mailing:recipient_list",
        "url_create": "mailing:recipient_create",
    },
    {
        "title": "Управление сообщениями",
        "list": "Список сообщенй",
        "create": "Создать",
        "update": "Обновить данные",
        "delete": "Удалить",
        "unique": "unic2",
        "url": "mailing:messages_list",
        "url_create": "mailing:message_create",
    },
    {
        "title": "Управление рассылками",
        "list": "Список рассылок",
        "create": "Создать",
        "update": "Обновить данные",
        "delete": "Удалить",
        "unique": "unic3",
        "url": "mailing:newsletter_list",
        "url_create": "mailing:newsletter_create",
    },
]


class ModerationMailingRecipientView(LoginRequiredMixin, PermissionRequiredMixin, CachedViewMixin, ListView):
    """Просмотр всех клиентов менеджером"""

    model = MailingRecipient
    context_object_name = "recipients"
    template_name = "mailing/moderation/list_recipient.html"
    permission_required = "mailing.view_all_mailing_recipient"

    def get_queryset(self):
        """Получает queryset, пытаясь использовать кэш."""
        queryset = self.get_cached_queryset()
        if queryset is not None:
            return queryset

        queryset = super().get_queryset()
        self.cache_queryset(queryset)
        return queryset


class ModerationNewsletterView(LoginRequiredMixin, PermissionRequiredMixin, CachedViewMixin, ListView):
    """Просмотр всех рассылок менеджером"""

    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailing/moderation/list_newsletter.html"
    permission_required = "mailing.view_all_newsletter"

    def get_queryset(self):
        """Получает queryset, пытаясь использовать кэш."""
        queryset = self.get_cached_queryset()
        if queryset is not None:
            return queryset

        queryset = super().get_queryset()
        self.cache_queryset(queryset)
        return queryset

    def post(self, request, pk):
        newsletter = get_object_or_404(Newsletter, id=pk)

        if not request.user.has_perm("mailing.disabling_mailings"):
            return HttpResponseForbidden("У вас нет прав для отключения рассылки.")

        newsletter.is_active = False
        newsletter.save()

        messages.success(request, f"Рассылка {newsletter} успешно отключена.")

        return redirect("mailing:newsletter_detail", pk=pk)


class ModerationUsersView(LoginRequiredMixin, PermissionRequiredMixin, CachedViewMixin, ListView):
    """Просмотр списка пользователей сервиса"""

    model = ModelUser
    context_object_name = "users"
    template_name = "mailing/moderation/list_users.html"
    permission_required = "users.can_block_user"

    def get_queryset(self):
        """Получает queryset, пытаясь использовать кэш."""
        queryset = self.get_cached_queryset()
        if queryset is not None:
            return queryset

        queryset = super().get_queryset()
        queryset = queryset.filter(groups__name="Пользователь")
        self.cache_queryset(queryset)

        return queryset

    def post(self, request, pk):
        user = get_object_or_404(ModelUser, id=pk)

        if not request.user.has_perm("users.can_block_user"):
            return HttpResponseForbidden("У вас нет прав для блокировки пользователей.")

        user.is_active = False
        user.save()

        messages.success(request, f"Пользователь {user.username} успешно заблокирован.")

        return redirect("mailing:moderation_user_list")


class ListIndex(ListView):
    """Главная страница"""

    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailing/index.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            user = self.request.user
            return queryset.filter(owner=user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        result = IndexCounter.count_newsletter(context)
        context["count_status"] = result[0]
        context["count_newsletter"] = result[1]
        context["unique_users"] = result[2]

        if self.request.user.is_authenticated:
            result_2 = IndexCounter.count_attempt_to_send(self.request.user)
            context["count_attempt_successful"] = result_2[0]
            context["count_attempt_fail"] = result_2[1]
            context["count_message"] = result_2[2]

        return context


class MailingRecipientView(CachedListView):
    """Получатель рассылки"""

    model = MailingRecipient
    context_object_name = "recipients"
    template_name = "mailing/list_recipient.html"


class MessageView(CachedListView):
    """Сообщение"""

    model = Message
    context_object_name = "messages"
    template_name = "mailing/list_message.html"


class NewsletterView(CachedListView):
    """Рассылка"""

    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailing/list_newsletter.html"


class MailingRecipientCreateView(CachedCreateView):
    """Получатель рассылки, создание"""

    model = MailingRecipient
    template_name = "mailing/create_recipient.html"
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailing:recipient_list")


class MessageCreateView(CachedCreateView):
    """Сообщение, создание"""

    model = Message
    template_name = "mailing/create_message.html"
    form_class = MessageForm
    success_url = reverse_lazy("mailing:messages_list")


class NewsletterCreateView(CachedCreateView):
    """Рассылка, создание"""

    model = Newsletter
    template_name = "mailing/create_newsletter.html"
    form_class = NewsletterForm
    success_url = reverse_lazy("mailing:newsletter_list")

    def get_form_kwargs(self):
        """Добавляем текущего пользователя в kwargs для формы"""

        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


@method_decorator(cache_page(60 * 15), name="dispatch")
class MailingRecipientDetailView(DetailView):
    """Получатель рассылки, детали"""

    model = MailingRecipient
    context_object_name = "recipients"
    template_name = "mailing/detail_recipient.html"


@method_decorator(cache_page(60 * 15), name="dispatch")
class MessageDetailView(DetailView):
    """Сообщение, детали"""

    model = Message
    context_object_name = "messages"
    template_name = "mailing/detail_message.html"


class NewsletterDetailView(DetailView):
    """Рассылка, детали"""

    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailing/detail_newsletter.html"

    def post(self, request, *args, **kwargs):
        """Получение и изменение данных рассылки"""

        newsletter = self.get_object()
        newsletter.status = "started"
        newsletter.first_dispatch = datetime.datetime.now()
        newsletter.save()

        # создаем экземпляр для регистрации попыток рассылок в БД
        owner = newsletter.owner
        attempt = AttemptToSend(attempts=datetime.datetime.now(), status=False, newsletter=newsletter, owner=owner)

        # логика отправки сообщения
        try:
            self.send_newsletter(newsletter)
            newsletter.status = "completed"
            newsletter.end_dispatch = datetime.datetime.now()
            attempt.status = True
            attempt.server_response = "Рассылка успешно отправлена"
            messages.success(request, "Рассылка успешно отправлена.")
        except Exception as e:
            messages.error(request, f"Ошибка при отправке рассылки: {str(e)}")
            attempt.server_response = str(e)

        attempt.save()
        newsletter.save()
        return HttpResponseRedirect(reverse_lazy("mailing:newsletter_detail", args=[newsletter.id]))

    def send_newsletter(self, newsletter):
        """Метод для отправки сообщений newsletter."""
        recipients = newsletter.recipients.all()

        for recipient in recipients:
            self.send_emails(recipient.email, newsletter.text.title, newsletter.text.body_message)

    def send_emails(self, emails, subject, message):
        """Функция отправки email-сообщений."""

        send_mail(
            subject,
            message,
            from_email=None,
            recipient_list=[emails],
            fail_silently=False,
        )


class MailingRecipientUpdateView(PermissionRequiredMixin, CachedUpdateView):
    """Получатель рассылки, обновление"""

    model = MailingRecipient
    template_name = "mailing/create_recipient.html"
    form_class = MailingRecipientForm
    permission_required = "mailing.change_mailingrecipient"
    success_url = reverse_lazy("mailing:recipient_list")


class MessageUpdateView(PermissionRequiredMixin, CachedUpdateView):
    """Сообщение, обновление"""

    model = Message

mailing/templates/mailing/base.html
<!doctype html>
<html lang="ru">
<head>
    <script src="/static/js/color-modes.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/sidebars.css" rel="stylesheet">
</head>

<body>
{% load mail_tags %}
{% include 'mailing/includes/header.html' %}
<!-- Top tags menu -->
<main>
    <div class="container marketing">
        <div class="mt-5 row featurette">
            <div class="col-md-3">
                {% show_menu request %}
            </div>
            <div class="col-md-9">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div><!-- /.container -->
    <!-- FOOTER -->
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2017–2024 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
</main>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/sidebars.js"></script>
</body>
</html>

mailing/templates/mailing/create_message.html
{% extends 'mailing/base.html' %}
{% block title %}Создание сообщения{% endblock %}

{% block content %}

<h2 class="mt-2 text-center">{% if object %}Редактирование{% else %}Создание{% endif %} сообщения</h2>
<hr class="featurette-divider">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
            <p><label class="fs-5 ms-5" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }} </p>
            <div class="fs-6"> {{ f.errors }}</div>
            {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'mailing:recipient_list' %}" class="btn btn-primary">Отменить</a>
</form>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/create_newsletter.html
{% extends 'mailing/base.html' %}
{% block title %}Создание рассылки{% endblock %}

{% block content %}

<h2 class="mt-2 text-center">{% if object %}Редактирование{% else %}Создание{% endif %} рассылки</h2>
<hr class="featurette-divider">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
            <p><label class="fs-5 ms-5" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }} </p>
            <div class="fs-6"> {{ f.errors }}</div>
            {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'mailing:recipient_list' %}" class="btn btn-primary">Отменить</a>
</form>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/create_recipient.html
{% extends 'mailing/base.html' %}
{% block title %}Создание получателя{% endblock %}

{% block content %}
<h2 class="mt-2 text-center">{% if object %}Редактирование{% else %}Создание{% endif %} получателя</h2>
<hr class="featurette-divider">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
            <p><label class="fs-5 ms-5" for="{{ f.id_for_label }}">{{ f.label }}:</label> {{ f }} </p>
            <div class="fs-6"> {{ f.errors }}</div>
            {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'mailing:recipient_list' %}" class="btn btn-primary">Отменить</a>
</form>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/detail_message.html
{% extends 'mailing/base.html' %}
{% block title %}Детали сообщения{% endblock %}

{% block content %}

<hr class="featurette-divider">
<h1 class="mt-5 text-center">Детали сообщения</h1>
<div class="col-1"></div>
<div class="col-10">
    <div class="mt-5 card-body text-start">
        <p class="card-text">Заголовок: {{ object.title }}</p>
    <p>Текст сообщения: {{ object.body_message }}</p>
        </div>
    {% if user == object.owner %}
    <div class="mt-5">
    <a href="{% url 'mailing:message_update' object.pk %}" class="btn btn-secondary">Редактировать</a>
    <a href="{% url 'mailing:message_delete' object.pk %}" class="btn btn-danger">Удалить</a>
    <a href="{% url 'mailing:messages_list' %}" class="btn btn-light border-primary text-primary">Назад</a></div>
    {% endif %}
</div>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/detail_newsletter.html
{% extends 'mailing/base.html' %}
{% block title %}Детали сообщения{% endblock %}

{% block content %}

<h1 class="mt-5 text-center">Детали рассылки</h1>
<hr class="featurette-divider">
<div class="col-1"></div>
<div class="col-10">
    {% if object.is_active %}
    <form method="post">
        <div class="mt-5 card-body text-start">
            {% csrf_token %}
            <p>Название рассылки: {{ object.name }}</p>
            <p>Статус: {{ object.human_readable_status }}</p>
            <p>Сообщение: {{ object.text }}</p>

            {% with object.recipients.all as recipients %}
            <p>Получатели:</p>
            {% for r in recipients %}
            <p> {{ r.last_name }} {{ r.first_name }} {{ r.patronymic }}</p>
            {% endfor %}
            {% endwith %}

            <p>Дата и время первой отправки: {{ object.first_dispatch }}</p>
            <p>Дата и время окончания отправки: {{ object.end_dispatch }}</p>
        </div>
        {% if user == object.owner %}
        <div class="mt-5">
            <a href="{% url 'mailing:newsletter_update' object.pk %}" class="btn btn-secondary">Редактировать</a>
            <a href="{% url 'mailing:newsletter_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'mailing:newsletter_list' %}" class="btn btn-light border-primary text-primary">Назад</a>
        </div>
        <button type="submit" class="btn btn-primary mt-1">Запустить рассылку</button>
        {% endif %}
    </form>
    {% else %}
    <h3 class="mt-5 text-center">Данная рассылка отключена модератором</h3>
    {% endif %}
    {% if perms.mailing.disabling_mailings %}
    <form action="{% url 'mailing:moderation' object.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger border-primary text-light" type="submit">Заблокировать рассылку</button>
        <a href="{% url 'mailing:moderation_newsletter_list' %}" class="btn btn-light border-primary text-primary">Назад</a>
    </form>
    {% endif %}
</div>

<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/detail_recipient.html
{% extends 'mailing/base.html' %}
{% block title %}Детали сообщения{% endblock %}

{% block content %}

<h1 class="mt-5 text-center">Детали сообщения</h1>
<hr class="featurette-divider">
<div class="col-1"></div>
<div class="col-10">
    <div class="mt-5 card-body text-start">
        <p>Поулатель рассылки: {{ object.last_name }} {{ object.first_name }} </p>
        <p>Email: {{ object.email }}</p>

        {% if object.comment %}
        <p>Коментарий: {{ object.comment }}</p>
        {% endif %}

        {% with object.recipients.all as recipients %}
        <p>Рассылки:</p>
        {% for r in recipients %}
        <p> {{ r.name }} </p>
        {% endfor %}
        {% endwith %}
    </div>
    {% if user == object.owner %}
    <div class="mt-5">
        <a href="{% url 'mailing:recipient_update' object.slug %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'mailing:recipient_delete' object.slug %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'mailing:recipient_list' %}" class="btn btn-light border-primary text-primary">Назад</a></div>
    {% else %}
    <a href="{% url 'mailing:moderation_recipient_list' %}" class="btn btn-light border-primary text-primary">Назад</a>
    {% endif %}
</div>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/list_message.html
{% extends 'mailing/base.html' %}
{% block title %}Список сообщений{% endblock %}

{% block content %}

<h2 class="mt-2 text-center">Список сообщений</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Заголовок</th>
        <th scope="col">Сообщение</th>
        <th scope="col">Детали</th>
    </tr>
    </thead>
    <tbody>
    {% for message in messages %}
    <tr>
        <th scope="row">{{ message.id }}</th>
        <td>{{ message.title }}</td>
        <td>{{ message.body_message|truncatechars:200 }}</td>
        <td><a class="link" href="{% url 'mailing:message_detail' message.pk %}">Подробнее</a></td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4" class="text-center">Нет сообщений для отображения.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/list_newsletter.html
{% extends 'mailing/base.html' %}
{% block title %}Рассылка{% endblock %}

{% block content %}

<h2 class="mt-2 text-center">Рассылка</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Название рассылки</th>
        <th scope="col">Текст рассылки</th>
        <th scope="col">Статус</th>
        <th scope="col">Начало рассылки</th>
        <th scope="col">Окончание рассылки</th>
        <th scope="col">Детали</th>
    </tr>
    </thead>
    <tbody>
    {% for news in newsletter %}
    <tr>
        <th scope="row">{{ news.id }}</th>
        <td>{{ news.name }}</td>
        <td>{{ news.text }}</td>
        <td>{{ news.human_readable_status }}</td>
        <td>{{ news.first_dispatch }}</td>
        <td>{{ news.end_dispatch }}</td>
        <td><a class="link" href="{% url 'mailing:newsletter_detail' news.pk %}">Подробнее</a></td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="7" class="text-center">Нет рассылок для отображения.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/list_recipient.html
{% extends 'mailing/base.html' %}
{% block title %}Получатели рассылки{% endblock %}

{% block content %}

<h2 class="mt-2 text-center">Получатели рассылки</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
        <th scope="col">Email</th>
        <th scope="col">Детали</th>
    </tr>
    </thead>
    <tbody>
    {% for recipient in recipients %}
    <tr>
        <th scope="row">{{ recipient.id }}</th>
        <td>{{ recipient.last_name }}</td>
        <td>{{ recipient.first_name }}</td>
        {% if recipient.patronymic %}
        <td>{{ recipient.patronymic }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td>{{ recipient.email }}</td>
        <td><a class="link" href="{% url 'mailing:recipient_detail' recipient.slug %}">Подробнее</a></td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="7" class="text-center">Нет клиентов для отображения.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<hr class="featurette-divider">
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block title%}Удаление статьи{% endblock%}

{% block content %}
<h2 class="mt-5 text-center">Удаление сообщения</h2>
<div class="col-1"></div>
<div class="col-10">
    <div>
        <p>Хотите удалить: {{ object.title }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'mailing:messages_list' %}" class="btn btn-primary">Отменить</a>
        </form>
    </div>
</div>

{% endblock %}