config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.apps import UsersConfig

from . import views
from .forms import UserPasswordResetForm, UserSetPasswordForm

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home_page"), name="logout"),
    path("confirm/<str:token>/", views.email_verification, name="verification"),
    # Смена пароля
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            form_class=UserPasswordResetForm,
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=UserSetPasswordForm,
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    # Работа с профилем
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="profile"),
    path("profile_update/<int:pk>/", views.UserUpdateView.as_view(), name="profile_update"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ModelUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    avatar = models.ImageField(upload_to="avatars/", null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    token = models.CharField(max_length=100, null=True, blank=True, verbose_name="Токен")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "username",
    ]

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "пользователя"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "Can block user"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, UserCreationForm

from mailing.forms import MixinForms

from .models import ModelUser


class MixinValidPhoneNumber:
    """Миксин для проверки валидности номера телефона"""

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен состоять только из цифр")
        return phone_number


class UserAuthenticationForm(MixinForms, AuthenticationForm):
    """Форма авторизации"""

    pass


class UserPasswordResetForm(MixinForms, PasswordResetForm):
    """Форма ввода E-mail для сброса пароля"""

    pass


class UserSetPasswordForm(MixinForms, SetPasswordForm):
    """Форма сброса пароля"""

    pass


class CustomUserCreationForm(MixinForms, UserCreationForm, MixinValidPhoneNumber):
    """Форма регистрации профиля"""

    phone_number = forms.CharField(max_length=15, required=False, label="Номер телефона")
    username = forms.CharField(max_length=100, required=True)

    class Meta:
        model = ModelUser
        fields = (
            "email",
            "username",
            "phone_number",
            "password1",
            "password2",
        )


class ProfileUserForm(MixinForms, forms.ModelForm, MixinValidPhoneNumber):
    """Форма профиля"""

    class Meta:
        model = ModelUser
        fields = ("last_name", "first_name", "username", "phone_number")

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import CustomUserCreationForm, ProfileUserForm, UserAuthenticationForm
from users.models import ModelUser


class UserCreateView(CreateView):
    """Представление регистрации профиля"""

    model = ModelUser
    form_class = CustomUserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        """Верификация зарегистрированного пользователя"""
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/confirm/{token}/"

        self.send_welcome_mail(user.email, url)
        return super().form_valid(form)

    def send_welcome_mail(self, user_email, url):
        """Отправка приветственного сообщения"""
        subject = "Добро пожаловать на наш сайт"
        message = (
            f"Спасибо, что зарегистрировались в нашем интернет магазине!\n"
            f"Для подтверждения регистрации перейдите по ссылке {url}"
        )
        from_email = EMAIL_HOST_USER
        recipient_list = [
            user_email,
        ]
        send_mail(subject, message, from_email, recipient_list)


def email_verification(request, token):
    """Активация и добавление прав пользователю"""
    user = get_object_or_404(ModelUser, token=token)
    user.is_active = True
    group = Group.objects.get(name="Пользователь")
    user.groups.add(group)
    user.save()
    return redirect(reverse("users:login"))


class UserLoginView(LoginView):
    """Представление авторизации"""

    form_class = UserAuthenticationForm
    template_name = "users/login.html"


class UserDetailView(DetailView):
    """Представление профиля"""

    model = ModelUser
    template_name = "users/profile.html"
    context_object_name = "user"


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Представление редактирования профиля"""

    model = ModelUser
    form_class = ProfileUserForm
    template_name = "users/register.html"

    def get_success_url(self):
        return reverse_lazy("users:profile", kwargs={"pk": self.object.pk})

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block title %}login{% endblock %}

{% block content %}

<div class="col-10 mt-5">
    <h2>Вход на сайт</h2>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing/base.html' %}
{% load i18n %}


{% block content %}
<hr class="featurette-divider mt-5">
<h2>{% translate "New password" %}</h2>
<p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% translate 'Log in' %}</a></p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing/base.html' %}
{% load i18n static %}
{% block content %}

<hr class="featurette-divider mt-5">
<h2>{% translate "New password" %}</h2>
<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
<hr class="featurette-divider">

<form method="post">
    {% csrf_token %}
    <div class="form-row field-password1">
      {{ form.new_password1.errors }}
      <div class="flex-container">
        <label for="id_new_password1">{% translate 'New password:' %}</label>
        {{ form.new_password1 }}
      </div>
    </div>
    <div class="form-row field-password2">
      {{ form.new_password2.errors }}
      <div class="flex-container">
        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
        {{ form.new_password2 }}
      </div>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing/base.html' %}
{% load i18n %}

{% block content %}
<hr class="featurette-divider mt-5">
<h2>{% translate "Reset password" %}</h2>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}

<div class="col-10 mt-5">
    <hr class="featurette-divider">
    <h2>Восстановление пероля</h2>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сбросить по E-mail</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'mailing/base.html' %}
{% block title %} Профиль {{ user.username }}{% endblock %}

{% block content %}
<div class="col-10 mt-5">
    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="mt-3 fw-medium text-center lh-1">{{ user.first_name }} {{ user.last_name }}</h2>
            <h5 class="mt-3 fw-medium text lh-1">Никнейм: {{ user.username }}</h5>
            <h5 class="mt-3 fw-medium text lh-1">Email: {{ user.email }}</h5>
            <h5 class="mt-3 fw-medium text lh-1">Страна: {{ user.country }}</h5>
            <h5 class="mt-3 fw-medium text lh-1">Дата регистрации: {{ user.date_joined }}</h5>
            <h5 class="mt-3 fw-medium text lh-1">Номер телефона: {{ user.phone_number }}</h5>
            <div class="d-flex flex-row mt-5">
                <a href="{% url 'users:profile_update' user.pk %}" class="btn btn btn-secondary " role="button">Редактировать</a>
            </div>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="rounded float-start img-fluid" width="500" height="500" src="{% if user.avatar %}{{ user.avatar.url }}{% else %}../../media/avatars/unnamed.jpg{% endif %}">
        </div>
    </div>
</div>


<hr class="featurette-divider">
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block title %}{% if object %}Редактирование профиля{% else %}Регистрация{% endif %}{% endblock %}

{% block content %}

<div class="col-10 mt-5">
    <h2>Регистрация</h2>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% if object %}Применить{% else %}Зарегистрироваться{% endif %}</button>
        </form>
    </div>
</div>

{% endblock %}